name: PnL-Monitor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
    - yfinance>=1.2.0
    - pandas>=2.3.0
    - matplotlib>=3.10.0
    - squarify>=0.4.3
    - sv-ttk>=2.6.0
    - claudedev_shared
